# fly.stg.toml app configuration file generated for api-staging-reavpages on 2024-09-24T21:16:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-staging-reavpages'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
